In [163]:
###================================ Problem statement with dataset find here =========================================

##https://www.kaggle.com/uciml/zoo-animal-classification

###====================================================================================================================
## classify the Animal in Zoo
##There are 16 variables with various traits to describe the animals. The 7 Class Types are: Mammal, Bird, Reptile, Fish, Amphibian, Bug and Invertebrate

##The purpose for this dataset is to be able to predict the classification of the animals, based upon the variables.

import numpy as np
import matplotlib.pyplot as plt

import pandas

dataset = pandas.read_csv('zoo.csv')

#print(dataset)

X,y = dataset.loc[:, dataset.columns != "animal_name"],dataset.class_type
## Ensure that the string which is Animal Name here is taken as parameter to exclude while creating input dataset
print(" variables observations  ",X.shape)
print(" Target Observation " , y.shape)

from sklearn import preprocessing
le = preprocessing.LabelEncoder()
le.fit(dataset.animal_name)





 variables observations   (101, 17)
 Target Observation  (101,)


LabelEncoder()

In [164]:

from sklearn.model_selection import train_test_split

X_train, X_test, train_y, test_y = train_test_split(X, y, test_size=0.25, random_state=1234,stratify=y)
#### Stratefication NOT working across all variables here??

print('All:', np.bincount(y) / float(len(y)) * 100.0)
print('Training:', np.bincount(train_y) / float(len(train_y)) * 100.0)
print('Test:', np.bincount(test_y) / float(len(test_y)) * 100.0)



All: [  0.    40.59  19.8    4.95  12.87   3.96   7.92   9.9 ]
Training: [  0.    40.    20.     5.33  13.33   4.     8.     9.33]
Test: [  0.    42.31  19.23   3.85  11.54   3.85   7.69  11.54]


In [165]:
from sklearn.tree import DecisionTreeClassifier

clf_gini = DecisionTreeClassifier(criterion = "gini", random_state = 100,
                               max_depth=1, min_samples_leaf=5)
clf_gini.fit(X_train, y_train)





DecisionTreeClassifier(class_weight=None, criterion='gini', max_depth=1,
            max_features=None, max_leaf_nodes=None,
            min_impurity_split=1e-07, min_samples_leaf=5,
            min_samples_split=2, min_weight_fraction_leaf=0.0,
            presort=False, random_state=100, splitter='best')

In [166]:
from sklearn import tree

tree.export_graphviz(clf,out_file='tree.pdf')


y_pred = clf_gini.predict(X_test)
print(y_pred)

[1 1 1 1 1 1 1 1 7 7 1 1 1 1 1 1 7 7 1 1 1 1 1 1 1 1]


In [167]:
from sklearn.metrics import accuracy_score
print ("Accuracy is ", accuracy_score(y_test,y_pred)*100)

Accuracy is  38.4615384615


In [168]:
print('Samples correctly classified:')
correct_idx = np.where(y_pred == y_test)[0]
print(correct_idx)

print('\nSamples incorrectly classified:')
incorrect_idx = np.where(y_pred != y_test)[0]
print(incorrect_idx)

Samples correctly classified:
[ 0  1  2  3  4  6  7 15 19 24]

Samples incorrectly classified:
[ 5  8  9 10 11 12 13 14 16 17 18 20 21 22 23 25]


In [169]:
from sklearn.metrics import confusion_matrix


print(confusion_matrix(y_test, y_pred))

[[10  0  0  0  0  0  3]
 [ 1  0  0  0  0  0  1]
 [ 1  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]
 [ 4  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0]]
